### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'str' and 'str'

### ISSUE THREAD

**Issue by Walleloveeve** [voldikss/AutoLogin#2]
使用Python3执行报错如下：
`Traceback (most recent call last):
  File "readfree.py", line 108, in <module>
    main()
  File "readfree.py", line 97, in main
    elif (cookies["csrftoken"] & cookies["sessionid"]):
TypeError: unsupported operand type(s) for &: 'str' and 'str'
`
修改readfree.py脚本中第97行后正常运行：
`elif (cookies["csrftoken"] and cookies["sessionid"]):`

**Comment by voldikss** [comment]
谢谢你
