### ISSUE TITLE
README.md 中的crontab定时任务格式错误

### ISSUE THREAD

**Issue by Walleloveeve** [voldikss/AutoLogin#3]
3 31 0,12 * * * python3 /root/autoLogin/readfree.py
24 31 0,12 * * * python3 /root/autoLogin/aixinwu.py

应该为：

31 0,12 * * * python3 /root/autoLogin/readfree.py
31 0,12 * * * python3 /root/autoLogin/aixinwu.py

**Comment by voldikss** [comment]
感谢，已修正

**Comment by Walleloveeve** [comment]
哈哈，感谢你做这个项目，帮我节省了很多时间和精力！

**Comment by voldikss** [comment]
不客气哈哈，感谢你帮我修改错误。我刚刚试了下还有一些问题导致登录不成功，有时间我再修修。

**Comment by Walleloveeve** [comment]
我在16.04.1-Ubuntu上验证能正常使用

**Comment by voldikss** [comment]
嗯是的，你应该是用 cookies 登录的，如果是用密码＋验证码的登录方式就登不上

**Comment by Walleloveeve** [comment]
嗯，是的。我用的cookies登录。
用密码＋验证码的登录方式是每次都要手动输入验证码吗？不打开浏览器怎么浏览验证码图片呢？
是自动识别验证码输入吗？

**Comment by voldikss** [comment]
是的，从命令行输入验证码。验证码会下载到本地。

**Comment by Walleloveeve** [comment]
哈哈，那样岂不是很麻烦了。还需要人工介入。
还是用cookies的好，正好这个网站也支持cookies登录。cookies有效期1年，一年赚的额度也够用很久了。到期了再更新一次cookies就行了

**Comment by voldikss** [comment]
嗯其实是第一次用密码登录后也会把 cookies 保存下来，以后仍然也是用　cookies 登录的。

你怎么知道　cookies 的有效期是一年的呢

**Comment by Walleloveeve** [comment]
我从cookie中看到csrftoken的有效期为364天。

**Comment by voldikss** [comment]
哦哦，364天 那还好

**Comment by Walleloveeve** [comment]
cookies的信息里面也写了过期时间和生存期，都是364天。
expires=Fri, 28 Feb 2020 03:37:54 GMT; Max-Age=31449600;

**Comment by voldikss** [comment]
嗯嗯，谢谢你，我刚刚也看到了

**Comment by Walleloveeve** [comment]
恩恩，不客气。你做的这个项目帮我节省了非常多的时间和精力。非常感谢，继续加油哦！↖(^ω^)↗

**Comment by voldikss** [comment]
嗯嗯～
